[package]
name = "jtrace"
version = "0.1.0"
authors = ["Bartosz Wojcik <bartwojc@gmail.com>"]
edition = "2018"

[dependencies]
capstone = "0.6.0"
clap = "2.33.0"
env_logger = "0.6.1"
exitfailure = "0.5.1"
fasthash = "0.4.0"
log = "0.4.6"
nix = "0.13.0"
proc-maps = "0.1.5"
structopt = "0.2.15"
